# Generated by Django 5.0.1 on 2024-01-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='UUID'),
        ),
    ]
