# Generated by Django 5.0.1 on 2024-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date_alter_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.TextField(max_length=100, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(max_length=40, unique=True, verbose_name='UUID'),
        ),
    ]
