# Generated by Django 5.0.1 on 2024-01-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_date_alter_task_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uuid',
        ),
    ]
