# Generated by Django 5.0.1 on 2024-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='No uuid', max_length=40, unique=True, verbose_name='uuid'),
        ),
    ]
