# Generated by Django 5.0.1 on 2024-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(max_length=40, verbose_name='uuid'),
        ),
    ]
